---

- name: Installing and configuring Docker
  hosts: all
  gather_facts: yes
  become: yes
  roles:
    - { role: docker, tags: ["docker"] }

- name: Setting up Rancher Server
  hosts: rancher
  gather_facts: yes
  become: yes
  roles:
    - { role: rancher, tags: ["rancher"] }

- name: Register Rancher Hosts
  hosts: rancher
  gather_facts: yes
  become: yes
  roles:
    - { role: rancher_reg, tags: ["rancher_reg"] }

- name: Deploy MySQL Container
  hosts: database
  gather_facts: yes
  become: yes
  roles:
      - { role: mysql_docker, tags: ["mysql_docker"] }

- name: Deploy WordPress App
  hosts: "application"
  gather_facts: yes
  become: yes
  roles:
    - { role: wordpress_docker, tags: ["wordpress_docker"] }